# Generated by Django 2.1.5 on 2019-03-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='short_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
